In [1]:
import pandas as pd
import random
import datetime as dt
from faker import Faker

In [2]:
df = pd.read_csv('../datasets/test_dataset1.csv', parse_dates=['purchased_date'])

In [3]:
df['email'] = (df.name.str.replace('\s+', '.') + '@gmail.com').str.lower()

In [5]:
df

,user_id,name,item_name,price,category_id,quantity,purchased_date,email
0,1004,Donna Martin,TV,199.95,14,1,2020-04-04,donna.martin@gmail.com
1,1004,Donna Martin,Vaccum,95.12,15,2,2020-05-12,donna.martin@gmail.com
2,1003,Bobby Bradley,Cup,12.76,44,1,2020-05-13,bobby.bradley@gmail.com
3,1011,Austin Thomas,Plate,5.55,156,1,2020-05-14,austin.thomas@gmail.com
4,1000,Jonathan Medina,Lotion,4.44,23,2,2020-05-15,jonathan.medina@gmail.com
5,1000,Jonathan Medina,Toothbrush,5.96,123,1,2020-05-16,jonathan.medina@gmail.com
6,1019,Brandon Beasley,Sanitizer,2.23,12,3,2020-05-17,brandon.beasley@gmail.com
7,1011,Austin Thomas,Wine,15.67,122,1,2020-04-04,austin.thomas@gmail.com
8,1014,Susan Morales,Yoga mat,45.53,1212,2,2020-04-05,susan.morales@gmail.com
9,1001,Rachael Massey,Beer,2.45,42,4,2020-04-06,rachael.massey@gmail.com
10,1005,Ross Strickland,Coffee,8.45,356,5,2020-04-07,ross.strickland@gmail.com
11,1014,Susan Morales,Lotion,4.44,23,3,2020-04-08,susan.morales@gmail.com
12,1020,Jennifer Cox,Coffee,8.45,356,4,2020-04-09,jennifer.cox@gmail.com
13,1001,Danny Lynn DDS,TV,199.95,14,2,2020-04-10,danny.lynn.dds@gmail.com
14,1019,Brandon Beasley,Vaccum,95.12,15,6,2020-05-06,brandon.beasley@gmail.com
15,1006,Ashley Nichols,Sanitizer,2.23,12,1,2020-05-07,ashley.nichols@gmail.com
16,1015,Angela Oneill,Wine,15.67,122,2,2020-05-08,angela.oneill@gmail.com
17,1009,Cody Moreno,Plate,5.55,156,4,2020-05-09,cody.moreno@gmail.com
18,1005,Douglas Atkinson,TV,199.95,14,1,2020-05-10,douglas.atkinson@gmail.com
19,1016,Ellen Mccarthy,Vaccum,95.12,15,1,2020-05-11,ellen.mccarthy@gmail.com

In [4]:
df.to_csv('../datasets/test_dataset1.csv', index=False)